title: <p align="center"> Gitesh Bhardwaj</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gitesh-b-7747a68a/">LinkedIn</a> |
  <a href=" https://github.com/GiteshSydney/">GitHub</a>
  
  <br>   
  I'm working on Fraud Detection Project.
  <br>
  </p>



theme: jekyll-theme-minimal
